name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "0 4 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUBTOKEN }}

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run the makefile to make the image and push it to DockerHub
      run: make build push

    - name: tag the image so it can be sent to gchr.io
      run: docker tag docker-spyserver ghcr.io/t288msd/docker-spyserver:latest

    - name: push to ghcr.io
      run: docker push ghcr.io/t288msd/docker-spyserver:latest
    
