name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "0 4 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

   # - name: configure
    #  run: ./configure

    - name: Make
      run: make build push

   # - name: Run check
   #   run: make check

   # - name: Run distcheck
   #   run: make distcheck
